### ISSUE TITLE
Is there any way to do slicing?

### ISSUE THREAD

**Issue by benboughton1** [buckthorndev/matrix2d#3]
Is there a way to do array slicing as per this numpy example?

https://www.w3schools.com/python/numpy/trypython.asp?filename=demo_numpy_array_slicing_2d3

**Comment by NazeemNato** [comment]
yes :)  added slicing support (latest version)

````dart

 var sliceArray = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
  ];

  var newArray = m2d.slice(sliceArray, [0, 2], [1, 4]);
  print(newArray);
// [[2, 3, 4],[7, 8, 9]]

````

**Comment by benboughton1** [comment]
Fantastic. Thank-you @NazeemNato
